;; avy
(when (package-installed-p 'avy)
  (avy-setup-default)
  (require 'avy-zap)
  (avy-setup-default)
;  (global-set-key (kbd "C-:") 'avy-goto-char)
  (global-set-key (kbd "C-'") 'avy-goto-char)
  (global-set-key (kbd "M-g f") 'avy-goto-line)
  (global-set-key (kbd "M-g w") 'avy-goto-word-1)
  (global-set-key (kbd "M-g e") 'avy-goto-word-0)
  (global-set-key (kbd "M-z") 'avy-zap-to-char))
