(when (eq (window-system) 'w32)
  (setq initial-frame-alist
        '((top . 0) (left . 0)
          (height . 65) (width . 95))))
(set-face-attribute 'default nil :family "Myrica M" :height 120)

(set-default 'buffer-file-coding-system 'utf-8)
(set-default 'default-process-coding-system '(utf-8-dos . cp932))
(add-to-list 'process-coding-system-alist '("git" utf-8-dos . utf-8-unix))
(add-to-list 'process-coding-system-alist '("Git.Exe" utf-8-dos . utf-8-unix))
(add-to-list 'process-coding-system-alist '("git.EXE" utf-8-dos . utf-8-unix))
(add-to-list 'process-coding-system-alist '("rubocop" utf-8-dos . utf-8-unix))
(add-to-list 'process-coding-system-alist '("ipconfig" cp932 . cp932))
(add-to-list 'process-coding-system-alist '("tracert" cp932 . cp932))
(add-to-list 'process-coding-system-alist '("ping" cp932 . cp932))
(add-to-list 'process-coding-system-alist '("netstat" cp932 . cp932))
(add-to-list 'process-coding-system-alist '("arp" cp932 . cp932))
(add-to-list 'process-coding-system-alist '("nslookup" cp932 . cp932))

(setq w32-rwindow-modifier (quote meta))
